### ISSUE TITLE
How to compile for ARM64

### ISSUE THREAD

**Issue by OriolOMM** [martinh/libconfuse#100]
Hi, first of all thanks for that library.

I'm would like to use this library into iOS project. How I can compile the library for ARM64?

Thanks!

**Comment by troglobit** [comment]
Hi,

I have little to no experience with macOS and none with iOS, so unfortunately I cannot help you there. However, libConfuse is a *GNU Configure & Build* based project, so it is possible to cross-compile using the standard mechanisms for that.  Usually `./configure --host=toolchain-prefix` or similar works.  

In my own little hobby OS, [TroglOS](https://github.com/troglobit/troglos/blob/master/lib/confuse/Makefile), I use the following:

Say my cross-toolchain is located here

    /usr/local/arm-unknown-linux-gnueabi-6.2.0-1/bin/arm-unknown-linux-gnueabi-gcc

Then I have that added to my `$PATH`

    export PATH=/usr/local/arm-unknown-linux-gnueabi-6.2.0-1/bin:$PATH

and I call the libConfuse `configure` script like this:

    ./configure --host=arm-unknown-linux-gnueabi --prefix= --disable-examples

The configure script figures out everything else by itself.  I'm guessing building apps for iOS has some similar framework for calling the configure script ... but like I said, I don't know any more than that.

**Comment by troglobit** [comment]
@OriolOMM Do you require further assistance, or can we close this issue with libConfuse?

**Comment by OriolOMM** [comment]
Hi, thanks for your answer.

I'm still trying to do it.

I did the same procedure that you told me in a Linux machine. After ./configure --host=arm-unknown-linux-gnueabi --prefix= --disable-examples I run make and make install. Then I browse to lib folder and run $file arm/lib/libconfuse.so.1.1.0, and the output is:

arm/lib/libconfuse.so.1.1.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=905d3883e3375f9ad4d9a3a4d66db6eec356b1df, not stripped


As you can see, x86-64.

Any suggestion?

Thanks

**Comment by fhunleth** [comment]
Could you try defining the `CC` variable so that it points your the crosscompiler? E.g.,
```
CC=arm-unknown-linux-gnueabi-gcc ./configure --prefix= --disable-examples
```
I'm not sure why I'm not using `--host` in my cross building scripts, but something close to the above is what I've been using.

**Comment by OriolOMM** [comment]
Hi, finally I have managed to compile for iOS.

I used this scripts to do it https://github.com/intlres1/iOS-autoconf

Thanks!!!!

**Comment by troglobit** [comment]
Good, then we can close this issue. Thank you for checking back, and thanks to @fhunleth for helping out as well! :)
