### ISSUE TITLE
Fix for #92 causes ABI break

### ISSUE THREAD

**Issue by sur5r** [martinh/libconfuse#101]
0285479 introduced a new field `comment` in the middle of `struct cfg_t` which causes an ABI break.

See
* i3/i3status#224
* https://bugs.debian.org/872078

Seems #81 does not catch this.

**Comment by DaveDavenport** [comment]
It is mentioned [here](https://abi-laboratory.pro/tracker/compat_report/libconfuse/3.0/3.1/8cf20/abi_compat_report.html) in the 3.1 release.

Is something like [libtool versioning](https://www.sourceware.org/autobook/autobook/autobook_61.html) not smart to use?

**Comment by wRAR** [comment]
Unfortunately, the libtool doc doesn't teach which changes are backward compatible and which aren't. Changing field offsets in a struct isn't.

**Comment by DaveDavenport** [comment]
No it does not. (But it still has added value as it provide more info for the rt linker.)

**Comment by troglobit** [comment]
So, move the comment field to the end and keep the ABI version or bump it for a v3.2.1 bug fix release?

**Comment by sur5r** [comment]
As both 3.1 and 3,2 are "out there" I would consider a bump the correct fix. That aside, I would not move the comment field around unless there are other reasons to do so.

**Comment by DaveDavenport** [comment]
I would strongly recommend against an abi break to fix an abi break. 
IMHO a bump would be the right fix. 

(p.s. thanks for the great library).

**Comment by troglobit** [comment]
OK, ABI bump for v3.2.1 seemed the sane choice for me as well. But with so many interested parties I thought it only prudent to ask.

I'll get right on the release work in a day or two. 

It's going to be the last release in a while, so if you guys have anything else you want fixed, it's time to pipe up :)

Otherwise, thanks for the awesome report and the kind words!

**Comment by sur5r** [comment]
OT for this issue, but, as you asked and before I open a new one:

There is [Debian #462251](https://bugs.debian.org/462251) sitting around and I can't find it among the closed github issues.

**Comment by troglobit** [comment]
@sur5r Ah, that one ... yeah someone should double check that `myvar = "${HOME}/path"` is still an issue before we at least file a corresponding issue here.

**Comment by troglobit** [comment]
I've checked this now,  [Debian #462251](https://bugs.debian.org/462251) was fixed by @fhunleth in commit 80fad81, which was released in libConfuse v2.8.  We even have a unit test for it.

Debian has some catching up to do.  I'll send an update to the Debian bug shortly.

**Comment by troglobit** [comment]
There, fixed and relased [v3.2.1](https://github.com/martinh/libconfuse/releases/tag/v3.2.1).

Big thank you to everyone that contributed to to this!
