### ISSUE TITLE
AM_GNU_GETTEXT error

### ISSUE THREAD

**Issue by pietercardoen** [martinh/libconfuse#107]
error: possibly undefined macro: AM_GNU_GETTEXT
error: possibly undefined macro: AM_GNU_GETTEXT_VERSION

I get these errors on ubuntu 16.04 LTS

How can I fix this?

Best regards
Pieter

**Comment by pietercardoen** [comment]
Fixed: inherit gettext in yocto fixes this but now I got:

| configure.ac:15: installing 'support/compile'
| configure.ac:32: error: required file 'support/config.rpath' not found

**Comment by troglobit** [comment]
No reply from reporter within a reasonable timeframe, closing.
