### ISSUE TITLE
There are compile errors in strdup implementation

### ISSUE THREAD

**Issue by tfarina** [martinh/libconfuse#113]
../confuse.c:118:15: error: use of undeclared identifier 'str'
        siz = strlen(str) + 1;
                     ^
../confuse.c:123:15: error: use of undeclared identifier 'str'
        memcpy(copy, str, siz);

The fix could be either change the parameter to 'str' or change usage of 'str' in the function body to 's'.

**Comment by troglobit** [comment]
Well, that's an obvious fix.  But what's not obvious is what system you are building libConfuse for?  Not having `strdup()` is very rare, unless you're building for a very stripped down non-POSIX compliant embedded system.
