### ISSUE TITLE
confuse.mo no such file or directory - I am following the instructions for building - to no avail

### ISSUE THREAD

**Issue by AnthonyTheKoala** [martinh/libconfuse#114]
I follow the instructions as per INSTALL document and do the following.
I have Win 7 and git bash console.```

invoke the git bash console.

cd c:/python36/confuse-3.2
./configure   # goes through all the checking - takes about one minute creates various files.
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating examples/Makefile
config.status: creating po/Makefile.in
config.status: creating m4/Makefile
config.status: creating tests/Makefile
config.status: creating doc/Makefile
config.status: creating doc/Doxyfile
config.status: creating libconfuse.pc
config.status: creating libconfuse.spec
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
sh: __git_ps1: command not found`

The last line `sh: __git_ps1:command not found `   # I don't understand how this may assist me. 

$ make
C:/mingw64/bin/make  all-recursive
make[1]: Entering directory 'C:/python36/confuse-3.2'
Making all in m4
make[2]: Entering directory 'C:/python36/confuse-3.2/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory 'C:/python36/confuse-3.2/m4'
Making all in po
make[2]: Entering directory 'C:/python36/confuse-3.2/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory 'C:/python36/confuse-3.2/po'
Making all in src
make[2]: Entering directory 'C:/python36/confuse-3.2/src'
C:/Program Files/Git/usr/bin/sh.exe ../libtool  --tag=CC   --mode=compile gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -DBUILDING_DLL   -g -O2 -MT libconfuse_la-confuse.lo -MD -MP -MF .deps/libconfuse_la-confuse.Tpo -c -o libconfuse_la-confuse.lo `test -f 'confuse.c' || echo './'`confuse.c
/usr/bin/sh: C:/Program: No such file or directory
make[2]: *** [makefile:479: libconfuse_la-confuse.lo] Error 127
make[2]: Leaving directory 'C:/python36/confuse-3.2/src'
make[1]: *** [makefile:521: all-recursive] Error 1
make[1]: Leaving directory 'C:/python36/confuse-3.2'
make: *** [makefile:407: all] Error 2
sh: __git_ps1: command not found

Why do I get all these errors, "no such file or directory" and sh:__git_ps1 command not found when I got the *.zip package confuse-3.2.zip without modifying it?

Thank you in advance,
Anthony of Sydney

**Comment by troglobit** [comment]
I hope some of the Windows users can chime in here, because my knowledge on the topic is very limited. However, I just successfully built confuse-3.2.2.zip on Windows 10 using both Cygwin and Mingw. So my bet is that it's something with your build environment.

(The sh:__git_ps1 error must be an issue with your "git bash" console, whatever that is, confuse has no reference to that.)

**Comment by troglobit** [comment]
Do you have `c:/mingw64/bin/` in your `PATH`?  The build system calls make to recursively build all sub-directories.

**Comment by AnthonyTheKoala** [comment]
Dear troglobit, 
Thank you for your reply.
I have been looking at ways of configuring the path in c:/mingw64/bin in the path. 

I went to Control Panel > System > Advanced System Settings (left side), went to Environment Settings and changed the environment variables and appended the following at the start of the path both local and user:.
These were:
c:/mingw64/bin;c:/mingw64/include/;c:/mingw64/lib

BUT I STILL GET THIS PROBLEM WHEN USING MAKE:

$ make
make  all-recursive
make[1]: Entering directory '/c/temp3/confuse-3.2'
Making all in m4
make[2]: Entering directory '/c/temp3/confuse-3.2/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/c/temp3/confuse-3.2/m4'
Making all in po
make[2]: Entering directory '/c/temp3/confuse-3.2/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/c/temp3/confuse-3.2/po'
Making all in src
make[2]: Entering directory '/c/temp3/confuse-3.2/src'
source='confuse.c' object='libconfuse_la-confuse.lo' libtool=yes \
DEPDIR=.deps depmode=none /bin/sh ../support/depcomp \
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -DBUILDING_DLL   -g -O2 -c -o libconfuse_la-confuse.lo `test -f 'confuse.c' || echo './'`confuse.c
libtool: compile:  gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I.. -D_GNU_SOURCE -DBUILDING_DLL -g -O2 -c confuse.c  -DDLL_EXPORT -DPIC -o .libs/libconfuse_la-confuse.o
../libtool: line 1765: gcc: command not found
make[2]: *** [Makefile:481: libconfuse_la-confuse.lo] Error 1
make[2]: Leaving directory '/c/temp3/confuse-3.2/src'
make[1]: *** [Makefile:521: all-recursive] Error 1
make[1]: Leaving directory '/c/temp3/confuse-3.2'
make: *** [Makefile:407: all] Error 2

Any other idea.?
I am looking for something that changes the path in the git bash terminal. Is it possible?

Thanks , tack, merci,  grazie, dunke, gracias in advance,
Anthony of

**Comment by AnthonyTheKoala** [comment]
Then I tried the following:
* restarted the machine with the new path:
* ran the make command
*result: the same kind of output
$ make
make  all-recursive
make[1]: Entering directory '/c/temp3/confuse-3.2'
Making all in m4
make[2]: Entering directory '/c/temp3/confuse-3.2/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/c/temp3/confuse-3.2/m4'
Making all in po
make[2]: Entering directory '/c/temp3/confuse-3.2/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/c/temp3/confuse-3.2/po'
Making all in src
make[2]: Entering directory '/c/temp3/confuse-3.2/src'
source='confuse.c' object='libconfuse_la-confuse.lo' libtool=yes \
DEPDIR=.deps depmode=none /bin/sh ../support/depcomp \
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -DBUILDING_DLL   -g -O2 -c -o libconfuse_la-confuse.lo `test -f 'confuse.c' || echo './'`confuse.c
libtool: compile:  gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I.. -D_GNU_SOURCE -DBUILDING_DLL -g -O2 -c confuse.c  -DDLL_EXPORT -DPIC -o .libs/libconfuse_la-confuse.o
../libtool: line 1765: gcc: command not found
make[2]: *** [Makefile:481: libconfuse_la-confuse.lo] Error 1
make[2]: Leaving directory '/c/temp3/confuse-3.2/src'
make[1]: *** [Makefile:521: all-recursive] Error 1
make[1]: Leaving directory '/c/temp3/confuse-3.2'
make: *** [Makefile:407: all] Error 2

* I had a similar result by copying all the bin files from c::/mingw64/bin to the c:/temp3/confuse-3.2 folder.
* running make install
* result still got the same problem.

Any ideas would be greatly appreciated including how to temporarily change the path in the git bash window.
Anthony of Sydney

**Comment by AnthonyTheKoala** [comment]
Particularly, the line 
../libtool: line 1765: gcc: command not found
Why is gcc not found?

Thank you in advance,
Anthony of Sydney

**Comment by troglobit** [comment]
Like I said before, I have little to no experience with Windows, I've been working exclusively with Linux and UNIX for the last 20 years.  However, it does look like your environment still isn't properly set up.

Previously make couldn't be found, but hat seems to be working now, what did you do to fix that?  Try running the gcc command from your shell prompt, if that doesn't work you need to add the path to that too.  

It looks like you're running Mingw, when I used that they had a simple .bat file I could run which set up PATH and started a neat shell for me.  Maybe the Mingw project is a better place to get support than this issue report, in particular since there does not seem to be any problem with libConfuse?

**Comment by AnthonyTheKoala** [comment]
I have reinstalled Git Bash. Interestingly, when I reinstalled, I chose not to add any paths from Git Bash to the path of my Win 7 machine and do not have problems when I configure., BUT when I compile using make I now get:

/usr/bin/sh: C:/Program: No such file or directory
make[2]: *** [makefile:479: libconfuse_la-confuse.lo] Error 127
Please see my observations below.
When I do 
./configure,    # I get no error. all necessary files for compilation are generated.

However when I compile by:
make               # I now get the following output
A@Anthony MINGW64 /c/temp3/confuse-3.2
$ make
C:/mingw64/bin/make  all-recursive
make[1]: Entering directory 'C:/temp3/confuse-3.2'
Making all in m4
make[2]: Entering directory 'C:/temp3/confuse-3.2/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory 'C:/temp3/confuse-3.2/m4'
Making all in po
make[2]: Entering directory 'C:/temp3/confuse-3.2/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory 'C:/temp3/confuse-3.2/po'
Making all in src
make[2]: Entering directory 'C:/temp3/confuse-3.2/src'
C:/Program Files/Git/usr/bin/sh.exe ../libtool  --tag=CC   --mode=compile gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -DBUILDING_DLL   -g -O2 -MT libconfuse_la-confuse.lo -MD -MP -MF .deps/libconfuse_la-confuse.Tpo -c -o libconfuse_la-confuse.lo `test -f 'confuse.c' || echo './'`confuse.c
/usr/bin/sh: C:/Program: No such file or directory
make[2]: *** [makefile:479: libconfuse_la-confuse.lo] Error 127
make[2]: Leaving directory 'C:/temp3/confuse-3.2/src'
make[1]: *** [makefile:521: all-recursive] Error 1
make[1]: Leaving directory 'C:/temp3/confuse-3.2'
make: *** [makefile:407: all] Error 2

Observation on:
/usr/bin/sh: C:/Program: No such file or directory
make[2]: *** [makefile:479: libconfuse_la-confuse.lo] Error 127

I googled the above observation. It appears that this problem is occurring in other projects. But it does not address my problem.

I know that usr/bin/sh refers to C:\Program Files\Git\bin. In the c:\Program Files\Git\bin are the programs bash.exe, sh.exe and git.sh.   I copied the bin directory to c:/usr/bin, compilation did not work. I copied bin directory to c:/temp3/confuse-3.2/usr and that did not work. I copied the bin directory to c:/temp3/usr and that did not work.

My question is it possible to do something like a git clone of confuse-3.2 and automatically compile and install it?

Thank you in advance,
Anthony of Sydney

**Comment by AnthonyTheKoala** [comment]
Finally have obtained no errors. Used cygwin64.
I did the following:
Ran the cygwin64 batch file/command window (in Win 7)
Performed the following commands in c:/temp3/confuse-3.2.

./configure     #remark no error message, found the gcc program. Configuration ran for a few minutes.
make install   #remark no error messages, the compilation went for a few minutes.

Note no error messages. 
BUT  I don't know where libconfuse.dll 

I did find the following files.

 Directory of C:\temp3\confuse-3.2\src\.libs
10/10/2018  10:18 PM    <DIR>          .
10/10/2018  10:18 PM    <DIR>          ..
10/10/2018  10:18 PM           292,365 cygconfuse-1.dll
10/10/2018  10:18 PM           183,528 libconfuse.a
10/10/2018  10:18 PM            74,876 libconfuse.dll.a
10/10/2018  10:18 PM               929 libconfuse.lai
10/10/2018  10:18 PM           124,904 libconfuse_la-confuse.o
10/10/2018  10:18 PM            56,084 libconfuse_la-lexer.o

Please excuse my knowledge of linux.
 
Is libconfuse.a library file?
Is libconfuse.dll.a a library file, but needs to be renamed libconfuse.dll?

No error messages, but want to know if the above files are the libconfuse library files.

Reason: I wish to put these in my c:/python36/scripts  such that I can use python and the ftdi library, located at https://www.intra2net.com/en/developer/libftdi/download.php

Thank you for your time.
Anthony of Sydney

**Comment by afonsoinfante** [comment]
Anthony,

If you're building libconfuse so you can use it with libftdi, please ask the libftdi folks for help... Even a cursory look at libftdi shows that it actually compiles libconfuse itself, and it does so using mingw, not cygwin, so you need to "feed" it the libconfuse source files, not the dll.

Again -- please ask the libftdi guys for help, we cannot help you here since this is definitely not a libconfuse issue at all.

Thanks.

**Comment by troglobit** [comment]
Thank you @afonsoinfante, I agree. We should probably close this issue.

@AnthonyTheKoala In general, when you've run configure and make, the process is to run `make install' to ensure the library files are stripped (and renamed depending on host system, I think Windows does this).  However, in this particular case you should probably follow the advise above and talk to the libftdi project instead.

**Comment by AnthonyTheKoala** [comment]
Yes, thank you for your patience,
According to another one of the installation instructions, it generates the *.a file. I have built *.a files before on my Win 7 system, It does not generate *.dll files.

So now, I will be pursuing the libftdi compilation and install it for Win 7. If there is an issue only with the libconfuse, I will raise a fresh issue.

Thank you for your time. I will now close the issue.
Anthony from exciting Sydney

**Comment by AnthonyTheKoala** [comment]
This issue is closed
