### ISSUE TITLE
visual studio compilation error

### ISSUE THREAD

**Issue by uglyoldbob** [martinh/libconfuse#117]
I am compiling libconfuse with visual studio 2015.

I get an error compiling fmemopen
fmemopen.c(161): fatal error C1189: #error:  Sorry, this platform currently has no fmemopen() replacement.

If I modify windows/msvs.net/config.h to add "#define HAVE_WINDOWS_H 1", it compiles.

**Comment by troglobit** [comment]
I have never tested libConfuse with Visual Studio, but I suspect that if Windows has fmemopen(), this could be a simple fix to the configure script. Care to give it a go?

**Comment by uglyoldbob** [comment]
I did a bit of compiling and research and determined that visual studio does not provide an fmemopen. Modifying the config.h for the windows project works. I'll put a brief pull request together.

**Comment by uglyoldbob** [comment]
I created a pull request with the modification
#118

**Comment by troglobit** [comment]
Great work! On most sane platforms we generate config.h based on the probe results from the configure script ...
