### ISSUE TITLE
How do I download older releases?

### ISSUE THREAD

**Issue by DoctorWho8** [martinh/libconfuse#122]
I only saw a new release shown. How do I download the versions 2.6 to 3.1?

On the original site pages it did show the older releases, but none of them are shown here.

**Comment by DoctorWho8** [comment]
Update: I found them, but it is not clearly defined where they are located.

**Comment by troglobit** [comment]
Do you mean you found http://download.savannah.gnu.org/releases/confuse/ in the README under the heading "Download" and item "Old releases"?

**Comment by troglobit** [comment]
Closing.
