### ISSUE TITLE
Writing to config files

### ISSUE THREAD

**Issue by davidgumberg** [martinh/libconfuse#123]
Would functions for appending to or editing existing values in config files be out of the scope of this library?

It may be the case that I am not correctly understanding the cfg_set... functions, as I am under the impression that those only set the state in cfg struct, I'm reading right now and if I discover this is not the case I'll close, sorry I posted issue prematurely.

**Comment by troglobit** [comment]
The API's that exist are part of [the documentation](https://www.nongnu.org/confuse/manual/confuse_8h.html#func-members).  There are also some examples that can be useful to look at, even the unit tests can be helpful although some of them may be a bit complex.

**Comment by davidgumberg** [comment]
Yeah, my issue was poorly written and I'm not sure that issue is even an appropriate term. My question is if an  API for writing or editing libconfuse config files is within the scope of the library.

**Comment by troglobit** [comment]
Aha, yes there is.  After `cfg_parse()` you can use the various APIs to edit, add, or remove settings, then you can use the `cfg_print()` and `cfg_print_indent()`.  Maybe not the most obvious name, but they take your resulting `cfg_t *` and writes it to the given `FILE *`.  You can test it out with `stdout`.

**Comment by troglobit** [comment]
@davidgumberg I'm closing this now, since it was more of a support ticket rather than an issue with libConfuse.
