### ISSUE TITLE
internal error in cfg_init_defaults

### ISSUE THREAD

**Issue by lurivasm** [martinh/libconfuse#124]
I am writing a project for my university and I have a problem that I cannot resolve.
This is my code, I have based on your example *simple.c*:

   `cfg_t *cfg;`
   `static char *server_root = NULL;`
   `static char *server_signature = NULL;`
   `static long int listen_port = 0;`
   `static long int max_clients = 0;`

   
  ` cfg_opt_t opts[] = {`
       `   CFG_SIMPLE_STR("server_root", &server_root),`
       `   CFG_SIMPLE_STR("server_signature", &server_signature),`
       `   CFG_SIMPLE_INT("listen_port", &listen_port),`
       `   CFG_SIMPLE_INT("max_clients", &max_clients),`
       `   CFG_END()`
    `};`

   `cfg = cfg_init(opts, 0);`
   `cfg_parse(cfg, "server.conf");`
   `cfg_free(cfg);`
   
And this is my *server.conf*:
`server_root="/home/practica1/www"`
`server_signature = "MiauServer 1.0"`
`listen_port = 9999`
`max_clients = 10`

However, I am having this problem:
`internal error in cfg_init_defaults(server_root)`
`Segmentation fault (`core' generado)`

How can I solve it?

**Comment by troglobit** [comment]
What version of libConfuse are you using?

**Comment by lurivasm** [comment]
The last version

**Comment by troglobit** [comment]
OK, I've just tested with the latest released version from GitHub and your code sample, using the contents of the .conf file you mention.  I experience no issue.

Have you tried running gdb on your binary and type 'bt full' when you get the segfault?

**Comment by lurivasm** [comment]
I got it, thank you!

**Comment by troglobit** [comment]
Great! So we can close this issue then?

**Comment by lurivasm** [comment]
Yes!
