### ISSUE TITLE
Cross compilation on windows with MinGW for ARM Cortex M3

### ISSUE THREAD

**Issue by ElMoe** [martinh/libconfuse#132]
Hello,

i am trying to compile libconfuse on windows with mingw for ARM Cortex M3. I have installed MinGW with gcc 8.2.0 with msys extension. I also installed the GNU Embedded Toolchain for ARM from [here](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads). I downloaded and extracted the .zip for libconfuse.

Then i tried to compile directly from the src folder from cmd-Box and with msys. For the later use it is recommended to compile with these attributes: -c -Wall -pedantic -mcpu=cortex-m3 -mthumb

I then got a lot of compiler errors, which i cannot cure in the source code:
![grafik](https://user-images.githubusercontent.com/15878068/73598071-cd67c500-4533-11ea-939d-4bbb95ad5f4e.png)

So the next idea was to use 'configure'. But as far as i found out from searching the configure script there is now way to set a '--host' attribute for ARM Cortex M3.

Last idea was to cheat the 'build.bat' and the 'makefile' but i don't have any idea to set the right values for CC and AR which are by default:

- CC=i686-pc-mingw32-gcc
- AR=i686-pc-mingw32-ar

Is there anybody who could guide me through the necessary steps? 

*DISCLAIMER:* I am not a proficient C-programmer nor am I very experienced with GNU compilers.

**Comment by troglobit** [comment]
I hope you downloaded the correct zip file. GitHub insists on automatically generating archives from the tag, which do not include all (generated) files.  The latest *release* zip is https://github.com/martinh/libconfuse/releases/download/v3.2.2/confuse-3.2.2.zip

For cross-compiling it is usually sufficient to:
1. Have the PATH variable set up to your toolchain
2. Call `./configure --host=toolchain-tuple-prefix`
3. `make`

With your toolchain the following should work:

    ./configure --host=i686-pc-mingw32

All (sane) configure based projects work the same, and there are lots of tutorials. available online.

**Comment by ElMoe** [comment]
As far as i can see, i downloaded the correct .zip.

Executing

`./configure --host=toolchain-tuple-prefix`

results in:
```
checking host system type... Invalid configuration `toolchain-tuple-prefix': machine `toolchain-tuple' not recognized
configure: error: /bin/sh support/config.sub toolchain-tuple-prefix failed
```

Executing

`./configure --host=i686-pc-mingw32`

runs the complete configure script, but mentioning:

`checking whether we are cross compiling... no`

Also not working:

`./configure --host=arm-none-eabi`

So i doubt that the configure script will generate the correct instructions for ARM Cortex M3. 

> All (sane) configure based projects work the same, and there are lots of tutorials. available online.

Yes, but the few out there are all different for cross compiling for ARM on Windows. But as i have written i am not very familiar with GCC.

**Comment by troglobit** [comment]
The tuple-prefix thing was just an example, I didn't think you'd take it literally.  Try this:

    ./configure --host=arm-none-eabi --build=`./support/config.guess`

It should detect that you're cross-compiling from your PC to Arm.

**Comment by ElMoe** [comment]
Ok, thank you for further support. When i execute your command, i get:
![grafik](https://user-images.githubusercontent.com/15878068/73611037-065c7400-45de-11ea-900b-a60fa7a42fd4.png)
The check - if the compiler is working - fails.
Here is what i found in the config.log:
![grafik](https://user-images.githubusercontent.com/15878068/73611119-eda08e00-45de-11ea-82bd-dda6a08ef1f9.png)
Shall i provide the complete log?

**Comment by troglobit** [comment]
From what I can see the linker in your toolchain cannot find the function _exit(), which its built-in C library references in its exit() function.   This is not a problem with libConfuse.

We're quickly approaching the border of what we can support you with in this project.  You are now entering cross-compiler territory, including setup issues with the same.  All I can tell you is that libConfuse cross-compiles fine, I do it myself in three different projects, including at work.  So I'm confident the issues you're having is not on our side.

**Comment by ElMoe** [comment]
> So I'm confident the issues you're having is not on our side.

Yes, you're right. But i think, i know now where i must look for. I will give it another try under Linux with a clean installation.
