### ISSUE TITLE
Possible to get a 3.2.3 release?

### ISSUE THREAD

**Issue by fhunleth** [martinh/libconfuse#140]
First, thanks for maintaining libconfuse. It has been super helpful.

I was wondering if you had plans for making a 3.2.3 release. I saw that there have been several updates since 3.2.2. For me, I'm seeing an uninitialized access in trim_whitespace() from valgrind that is fixed in e9f3dcf245d583833df838cb4d0f1b477ad3ecbc. I don't think it's causing an issue, but if you have time, it would be nice to get a release distributing around just in case.

Thanks!

**Comment by troglobit** [comment]
Hi Frank!  A release is coming, I've just been extremely busy at $DAYJOB the last couple months, there's also a late feature I'd like to get in there (last remaining PR).

**Comment by fhunleth** [comment]
Great! Thanks again - Frank

**Comment by troglobit** [comment]
@fhunleth Took a little while longer than planned -> https://github.com/martinh/libconfuse/releases/tag/v3.3
