### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by jimgeorge** [martinh/libconfuse#17]
I'm working with a small test program, very similar to the example given in tutorial step 4. When the example is run under valgrind, it reports a block that is "definitely lost", and another that is "still reachable". I'm using libconfuse from the CentOS 6.5 repositories, version 2.7. I installed the debuginfo packages, so valgrind gives me some symbolic info, but the line numbers are mangled, possibly due to compiler optimizations.

With some experimentation, I determined that the first loss record is the section name. My config file contains:

filter temp {
  name = "test filter"
  complex = true
  real_coeffs = {1, 2, 3, 4}
  imag_coeffs = {-1, -2, -3, -4}
}

Valgrind reports five bytes lost in a strdup call under cfg_parse_internal, and loses five bytes. If I edit the first line of the config file to read "filter temp1 {", the number of bytes lost goes up to six.

The second loss record is in cfg_parse_fp, a call to cfg_yy_switch_to_buffer.

I have called cfg_free on both the outer cfg_t (returned by cfg_parse) and the inner one (returned by cfg_getsec).

Please let me know if there's more I can do to help diagnose this.

**Comment by jimgeorge** [comment]
I forked this repo and was able to recreate the leaks on a locally-compiled version of the library. The first leak is easily fixable with a "free", I will submit a pull request for this.

The second one, well, I'm not very familiar with yylex so I'm not sure if it's easy to fix, or if it's even a real problem. It seems like a missing call to cfg_yylex_destroy(), but it's unclear to me if this has side effects.

**Comment by troglobit** [comment]
Should be fixed on master as of 64a5cb3, see also discussion in PR #18.
