### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by fhunleth** [martinh/libconfuse#23]
Could you make a 2.8 (or another release number) so that the bug fixed for issue #10 can be used by other projects more easily? My current situation is to refer to libconfuse via a hash tag or master which does not inspire as much confidence in others.

**Comment by troglobit** [comment]
A v2.8 release tag is coming up soon, I'll just do some basic housekeeping first.

**Comment by DavidEGrayson** [comment]
Thanks, I am looking in to making an MSYS2 package and having a recent tagged releases would help.

**Comment by DavidEGrayson** [comment]
The website at http://www.nongnu.org/confuse/ is out of date now since it doesn't mention the new release made today.

**Comment by troglobit** [comment]
I believe @martinh intended for everything to be migrated to GitHub, but it's a little bit confusing, despite the link there to GitHub.  I have a few other questions as well, so I'll ask him in due course.

**Comment by DavidEGrayson** [comment]
Sounds good.  It would be less confusing if all the information about library versions were removed from the old webpage.

**Comment by troglobit** [comment]
Yep.

Anyway, time to close this issue :+1:
