### ISSUE TITLE
Libtool version info has never been updated

### ISSUE THREAD

**Issue by peda-r** [martinh/libconfuse#30]
src/Makefile.am specifies "-version-info 0:0:0" when libtool links the libconfuse library, and has been doing that since basically forever. This is wrong.

For reference, read about libtool versioning in the libtool manual:

https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

However, please take particular note about this part if the version info is updated:

_**Never** try to set the interface numbers so that they correspond to the release number of your package._

**Comment by peda-r** [comment]
Heh, forever was wrong. version info was new for version 2.8.

My bad.

I'm closing this non-issue...

**Comment by troglobit** [comment]
It's a good question though. What policy we should have? I propose keeping the SO version as long as we remain ABI compatible backwards.

**Comment by peda-r** [comment]
The libtool page I referred to is quite clear on how this should be handled. I suggest the guidelines there are followed as closely as we are capable of.

**Comment by troglobit** [comment]
OK. I think we need a HACKING file, or similar to define rules like this in.
