### ISSUE TITLE
Unconditional call to setlocale() in cfg_init()

### ISSUE THREAD

**Issue by peda-r** [martinh/libconfuse#46]
setlocale might interfere with what the app wants, and a followup setlocale call might destroy the returned string from a previous setlocale call (by the app).

**Comment by troglobit** [comment]
Hmm, yeah you're right.  We should probably start by querying the current locale, using `NULL` as argument. 

Otoh, with `""` as argument libConfuse only uses the locale settings from the environment ... so not too bad.

**Comment by peda-r** [comment]
Any library calling functions with side effects are trouble. If a library calls setlocale with NULL, that may trample on the results returned by a previous query from the app.

Consider:
```
    foo = setlocale(LC_WHATEVER, so_what);
    if (!foo)
        handle_it();
    ...
    cfg = cfg_init(...);
    ...
    printf("%s\n", foo);
```
If cfg_init calls setlocale in any way, that may clobber foo.

Now, I realize that it might break stuff to simple remove the setlocale calls, but I really think it is the resposibility of the application to call setlocale *early*.

Maybe we could add a flag that makes cfg_init call setlocale for those who think it clobbers the application code? Or a flag to not call setlocale?

**Comment by troglobit** [comment]
The `setlocale()` syscall is a bit weird, to do "getlocale()" you call it with `NULL` argument. 
My idea was to do something like this:

    backup_foo = setlocale(LC_FOO, NULL);
    ...
    setlocale(LC_FOO, "");
    ...
    setlocale(LC_FOO, backup_foo);

**Comment by peda-r** [comment]
And that would be broken code, which is exactly the problem. The second call to setlocale (a library function btw, not a syscall) may clobber what the first setlocale call returned, so you effectively have to:
```
foo = setlocale(LC_FOO, NULL);
backup_foo = foo ? strdup(foo) : NULL;
...
setlocale(LC_FOO, "");
...
setlocale(LC_FOO, backup_foo);
```

But an unsuspecting application may not knwo that its state is clobbered by libconfuse, so it may not know that it has to do the same dance, i.e..

```
bar = setlocale(LC_BAR, NULL);
bar_backup = bar ? strdup(bar) : NULL;
...
cfg = cfg_init(...);
...
setlocale(LC_BAR, bar_backup);
```
instead of the simpler:
```
bar = setlocale(LC_BAR, NULL);
...
cfg = cfg_init(...);
...
setlocale(LC_BAR, bar);
```

**Comment by troglobit** [comment]
I really don't understand what's the problem here, maybe we're not talking about the same thing?

I tried to propose adding code in libConfuse to first backup the current locale settings, then change them for the sake of processing, and restore them to their backed up state before returning control the the application that called us.

I don't understand where we then would clobber anything for the application?

**Comment by peda-r** [comment]
setlocale may return the address of same static string (but with different content), i.e. there is simply no way to call it without clobbering a previously returned string.

This is no surprice really, since you are not required to free the returned string, so the sane implementatino of setlocale is to return the result some buffer that is allocated once.

**Comment by troglobit** [comment]
Ah, so *that's* what you meant.  Well then we'll just have `strdup()` the returned string for each locale value we want to backup. I see no problem with this.

**Comment by peda-r** [comment]
That is still no good, we would clobber any setlocale result the app intended to reuse across the call the cfg_init. Any strdup on our part would have zero impact.

**Comment by troglobit** [comment]
So your point, what it all boils down to, is that libConfuse should not mess around with `setlocale()` at all?

**Comment by troglobit** [comment]
... I should have read your first reply more thoroughly, that's indeed what you propose.  Although at that point I didn't realise the consequences of overriding a users call to `setlocale()` prior to `cfg_init()`.

My apologies, must have appeared slightly daft to you :smile:

**Comment by troglobit** [comment]
Having thought about this now a while I think we should remove it, no compat flags, just put it to the ChangeLog.

**Comment by peda-r** [comment]
Right, I don't see why any library should mess with that. It is totally up to the application to initialize the locale stuff. But, it should also be documented that it is the assumed that the application will actually call setlocale by itself, or else the gettext things probably fails...

**Comment by troglobit** [comment]
Exactly, yep that needs to be in the docs as well.

**Comment by troglobit** [comment]
@peda-r If you get a few minutes to spare, please take a look at PR #48. Thanks in advance!
