### ISSUE TITLE
Setting string lists with cfg_setopt() does not work

### ISSUE THREAD

**Issue by troglobit** [martinh/libconfuse#68]
Ran into this with Inadyn today. Tried to write a migrate-deprecated-setting function today for string lists, did not bite.  The code does not seem to support it?

https://github.com/martinh/libconfuse/blob/master/src/confuse.c#L646

**Comment by peda-r** [comment]
Have a look at how cfg_opt_setmulti() calls cfg_setopt().

Cheers,
Peter

**Comment by troglobit** [comment]
@peda-r Thanks! 

This can be greatly improved ...

**Comment by peda-r** [comment]
cfg_setopt() is just too low-level when it comes to lists and sections and can't really be used for those except if you also abuse libconfuse internals. It really is a plumbing function that just happens to do the right thing for the simpler option types.

**Comment by troglobit** [comment]
Hmm, I'm beginning to realize as much ... what I wanted was something along the lines of:

     value = cfg_get_optval(cfg, "old-setting");
     cfg_set_optval(cfg, "new-setting", value);

Which would transparently handle all different types.  I'm looking at whipping something up.

**Comment by peda-r** [comment]
The tough nut to crack is what the type of "value" should be. Since you didn't mention cfg_getopt() I take it that you did not mean that it should be cfg_opt_t *value?

**Comment by troglobit** [comment]
Well anything better than this troglobit/inadyn@5a679d9 ... would be good if Confuse could wrap this for our users.  Basically I just want to "rename" an option, or move its values to a new option of the same type.  

(This is the first time I get to practise this, but I've predicted many more such exercises for future projects at work, where we also use libConfuse.)
