### ISSUE TITLE
Cross compilation 

### ISSUE THREAD

**Issue by xoac** [martinh/libconfuse#70]
Hi guys I would like to use your library on mips target. I have cross compliator [here](http://openwrt.wk.cz/attitude_adjustment/mr-mips/). But you use some auto generation script. Is somebody who can explain what should I change to cross compile the library and then can link it to my project?

**Comment by xoac** [comment]
Additional info from eclipse
cross settings are:
prefix -- mips-openwrt-linux-
path -- /home/sylwek/iGT/OpenWrt-SDK-mr-mips-for-linux-i686-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_gcc-4.6-linaro_uClibc-0.9.33.2

I should do sth like this:
./configure --host=? CC=? --prefix=$HOME/libconfuse/libraryTOaddTOeclipse/

**Comment by troglobit** [comment]
Hi, you should use the released tarballs, not clone directly from GitHub. Using a GIT clone usually means you are a developer/contributor of libConfuse.  

The project does not host any generated files in GIT.  So the `configure` script, and Makefile templates (`Makefile.in`) have to be generated first with `./autogen.sh`, which requires you to have `autoconf`/`automake` et al.

The released tarballs include all the generated files. See 

https://github.com/martinh/libconfuse/releases

and for instance download and try this one:

https://github.com/martinh/libconfuse/releases/download/v3.0/confuse-3.0.tar.gz

To cross-compile you simply feed the configure script's `--host=mips-openwrt-linux` ... notice the missing dash at the end.  You need to have the toolchain in your PATH.

**Comment by xoac** [comment]
Thx. 
I needed --disable-examples.
and this:
`PATH=$PATH: (your toolchain/bin directory here)
export PATH
STAGING_DIR=(your toolchain directory here)
export STAGING_DIR
`

**Comment by xoac** [comment]
I have one more question. If I add the the libconfuse lib to -L and -l and compile my application and then copy binary to my target/host device and run this on target/host. Will I also need copy libconfuse.so library? 

It's just off-topic because I can test it tomorrow but I am curious.

**Comment by troglobit** [comment]
Depends on how you compile your application. If you build it to link statically to the
