### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by anonymous09** [martinh/libconfuse#78]
Time for new release?

**Comment by troglobit** [comment]
Coming, soon 😊👍

**Comment by troglobit** [comment]
Sorry for the delay, have been working on another project at work for the last couple of months.  Started working on libConfuse again today.

**Comment by anonymous09** [comment]
Good day! Any ETA?

**Comment by troglobit** [comment]
@anonymous09 Sadly no, still a few things on my TODO list before v3.1

**Comment by troglobit** [comment]
There, v3.1 released, finally! :smiley: 

https://github.com/martinh/libconfuse/releases/tag/v3.1
