### ISSUE TITLE
fmemopen() not available on *BSD/MacOS

### ISSUE THREAD

**Issue by springlie** [martinh/libconfuse#79]
When build on mac os, a error says that a linux glibc api "fmemopen" can't be found.
Maybe some bsd style apis can be used to replace the glibc apis, to make this library can be build successfully on the environment without glibc.
Or use https://github.com/NimbusKit/MemoryMapping.

**Comment by troglobit** [comment]
Thanks for the report!

I'll look into it during the weekend, shouldn't be too difficult. 😃

**Comment by springlie** [comment]
@troglobit It works well on my mac and thanks for your quick fix.

**Comment by troglobit** [comment]
@springlie Great to hear, thanks!  That means zero blockers for the 3.1 release :smiley:
