### ISSUE TITLE
Section title dupes

### ISSUE THREAD

**Issue by glasreiniger07** [martinh/libconfuse#86]
First: Great work is done here! I hate to write and maintain this kind of functionality for projects over and over again. This approach outstands standard INI-file alikes. 

I stumbled upon section title dupes:
with `CFG_SEC("Sensor", sensor_opts, CFGF_TITLE | CFGF_MULTI),`
file `Sensor title1 {} Sensor title2 {} ` works fine.
But without CFGF_NO_TITLE_DUPES set 
file: `Sensor title1 {} Sensor title1 {} ` drops the dupe silently.

A fix would be to report an parse error anyways, even if CFGF_NO_TITLE_DUPES is not set, 
or if there can be section title dupes logically, just not to search for them with the flag not set.

Because I'm on the rather old 2.7 release: Am I missing something regarding to this behavior?

**Comment by peda-r** [comment]
Yes, you are missing the fact that not every config option/section has to come from the same place. It can be useful to override previous config options/sections in e.g. an included config snippet.

**Comment by troglobit** [comment]
Thank you for your kind words, we have much to thank @martinh for :-)

Now, regarding your question, It's exactly like @peda-r says and the behavior in newer libConfuse releases is the same in this regard.

**Comment by glasreiniger07** [comment]
Oh, thanks for the quick response and explanation !
My solution is then to stop abusing section titles for `Sensor name {}` and introduce a real name option `Sensor {name = "ex-title"}.` Should have thought about that earlier...

**Comment by troglobit** [comment]
@glasreiniger07 No problem, good luck using libConfuse! :smiley:
