### ISSUE TITLE
Getting "internal compiler error" when using CFG_FLOAT in a c++ program

### ISSUE THREAD

**Issue by tibabit** [martinh/libconfuse#88]
Hi I am getting following error when using **CFG_FLOAT** in a c++ program

/home/vikash/projects/libconfuse-cpp/libconfuse/include/confuse.h:430:83: **internal compiler error**: in reshape_init_class, at cp/decl.c:5653
{name,CFGT_FLOAT,0,0,flags,0,{0,def,cfg_false,0,0},0,{.fpnumber=svalue},cb,0,0,0}

I am able to use other macros with no problem at all.

**I am using 6.3.0 on Ubuntu 17.04 and 64 bit machine architecture**

**Comment by troglobit** [comment]
Would you mind including a small example program so we can easily reproduce the problem?

**Comment by tibabit** [comment]
My mistake, was using it wrong.
Thanks anyway.

**Comment by troglobit** [comment]
OK :+1:
