### ISSUE TITLE
Why is it necessary to add a __unknown option  in a section

### ISSUE THREAD

**Issue by tibabit** [martinh/libconfuse#90]
I was wondering why is it necessary to add and '__unknown' option a section to ignore unknown options in addition to setting CFGF_IGNORE_UNKNOWN flag. Can't we do it by just setting the flag on the section or the whole file.

**Comment by troglobit** [comment]
This feature stems from PR #20, which admittedly could be handled better than the current need for mapping unknowns to `__unknown`.

Ran into the same problem the other day actually, wrote down this on my personal TODO list:
- "Actually ignore unknown options/sections, let parser skip forward"

If you have ideas how to do it, or further questions about the code, we could use this GitHub issue.

**Comment by troglobit** [comment]
Fixed in PR #91, if you can, I'd very much appreciate someone else testing it.
