### ISSUE TITLE
funopen() unavailable in gcc-mingw-w64-x86-64

### ISSUE THREAD

**Issue by fhunleth** [martinh/libconfuse#96]
In upgrading to libconfuse 3.1, I am now receiving the following error on mingw builds for Windows:
```
libconfuse.a(libconfuse_la-fmemopen.o): In function `fmemopen':
fmemopen.c:110: undefined reference to `funopen'
```
This can be reproduced on Debian/Ubuntu by installing the mingw crosscompiler:
```
sudo apt install gcc-mingw-w64-x86-64
cd confuse
CC=x86_64-w64-mingw32-gcc ./configure --enable-shared=no --disable-examples
make
```
Then try linking libconfuse.a to a trivial app. Since I never build the libconfuse examples in my Windows builds, I hadn't realized that they didn't compile with mingw, but in theory, they could show the issue too. If nothing else, you can see the warning the `funopen` isn't defined when compiling fmemopen.c.

I'm not completely sure how best to work around this issue. In the past when I've run into uses of fmemopen, it has been pretty easy to remove them, but I don't think that's the case here. However, I also don't know how one would implement fmemopen without funopen. Hence I'm posting here to see if there are any other ideas.

**Comment by fhunleth** [comment]
P.S. Sorry to not have caught this before the 3.1 release. I wasn't paying attention until after I received the 3.1 release email. :(

**Comment by troglobit** [comment]
That's unfortunate, `fmemopen()` is POSIX.1-2008 and usually systems that don't have it at least have `funopen()`.  Windows is not a primary target for the project, so I never tested there.

I added `fmemopen()` to libConfuse to make the code paths for parsing a file and parsing a buffer equal.  The reason was the massive amounts of memory leaks and code complexity in both the parser engine and the lexer.

Not really sure how to approach this, if there is anything in mingw that can emulate reading from a FILE like `fmemopen()` it should be straight forward.

**Comment by troglobit** [comment]
@fhunleth What do you think, should I pull the release ZIP (Windows) for v3.1, or just update the release notes with this limitation?

**Comment by fhunleth** [comment]
I'll have to dig a little deeper. I don't normally use Windows either, but I have a bunch of users of one of my projects on Windows. 

As for pulling the Windows release, I'm not sure that's necessary. I'm pretty sure that cygwin and Windows Bash mode users will be fine with v3.1. I don't know about Visual Studio users. Also, there's an off chance that the error is related to Ubuntu and Debian packaging old versions of mingw, since I've run into that before. Let me investigate when I get a break from some other work...

**Comment by peda-r** [comment]
There is no equivalent in MS libc. You'd have to redefine FILE, emulate fmemopen to generate a special FILE *, wrap all functions taking a FILE * and call out to helpers if the special memory backed FILE * show up. So, it can be done, but it's going to be ugly as hell and break whenever someone decides to use some new api (or some new aspect of a previously used api) taking a FILE *.

libconfuse is unusable to me if windows support is blown away like this. Please fix whatever problem was fixed with fmemopen in some other way. I have zero time to work on this right now.

**Comment by peda-r** [comment]
But of course, that above assumes that the redefined FILE doesn't need to be leaked out in the libconfuse API. Haven't checked that...

**Comment by troglobit** [comment]
@fhunleth OK, sounds reasonable, I'll keep the zip then.

**Comment by troglobit** [comment]
Guys, I'm sorry I've broken¹ your use-case.  Unfortunately I'm the only active maintainer atm and my time is very limited. Reverting to the situation before `fmemopen()` is not an alternative (massive memory leaks). 

Maybe on Windows `fmemopen()` could be implemented as a `tmpfile()`?  

___
¹ https://xkcd.com/1172/

**Comment by fhunleth** [comment]
@troglobit Thanks for maintaining libconfuse. It has saved me quite a bit of time, and it's reassuring to know that someone responds to bug reports (pretty quickly I might add).

I tried out a few things this morning: 
1. `tmpfile()` returns NULL on mingw-w64 4.0.4. It's deprecated in mingw-w64 5.0, so this doesn't look like a good option.
2. I tried `mkstemp()`, but it's segfaulting for me on mingw-w64 4.0.4.

I'll take another pass tomorrow.

**Comment by troglobit** [comment]
@fhunleth No problem, and thank you for the kind words.

Interesting to know of the deprecation of `tmpfile()`.  Windows has [some issues](https://msdn.microsoft.com/en-us/library/x8x7sakw.aspx) with this, seems it requires admin rights to create a tempfile?

I'll see if I can set up a small mingw-w64 enviroment to test some ideas myself.

**Comment by peda-r** [comment]
Regarding the xkcd link: Kill Windows support, and then ridicule any complainers, is that it?

**Comment by troglobit** [comment]
@peda-r That was really not my intention, I was simply trying to convey the humor of it all.

**Comment by troglobit** [comment]
On a more constructive note. Maybe this could help us?

https://sourceforge.net/p/mingw/msys2-runtime/ci/f21dc72d306bd98e55a08461a9530c4b0ce1dffe/tree/newlib/libc/stdio/fmemopen.c

**Comment by peda-r** [comment]
Nope, msys2 is a fork of Cygwin. I.e. a completely different libc.

**Comment by troglobit** [comment]
@peda-r Was thinking we could take that stand-alone implementation to replace our current [src/fmemopen.c](https://github.com/martinh/libconfuse/blob/master/src/fmemopen.c), at least on Windows. All it seemed to require from the OS was `sbrk()`?

**Comment by troglobit** [comment]
Hopefully, with PR #97 we can put this issue to rest.  I've done my best to test it with mingw and Wine on Linux, but I don't know if it works on Windows.

Also, I feel really bad about the whole direction this thread took. It was of course never my intention to break Windows with the work I did to fix the memory leaks in #75, or for that matter to inadvertently offend any of the users of libConfuse. I don't like that feeling this has left me with ...

So, if the fixes in #97 are to your satisfactory I'll merge them and release v3.2, which would likely be the last release I do.

**Comment by fhunleth** [comment]
I'll try this out tonight. From a brief skim, I expect it to fix the issue for me. Thank you so much for looking into this.

**Comment by peda-r** [comment]
@troglobit, you can't seriously consider stepping down over my heated remarks? I was just frustrated with the apparent disregard for Windows (which is all to common in various OSS projects, it gets very old). I'm truly sorry to have offended you, and I sincerely hope you reconsider!

**Comment by troglobit** [comment]
@peda-r Yes, yes I did actually. It is an uphill climb as it is, so that was just uncalled for. The simple reason for Windows not being a primary target is that I haven't used it in 20+ years. All projects live and die with their contributors, and that's all of us.

Now, let's move on and do some coding! :smiley:

**Comment by fhunleth** [comment]
@troglobit All of my project's regression tests pass on the Windows build, so I'm good with your PR!

**Comment by troglobit** [comment]
@fhunleth Awesome, thank you for testing it! I'll probably merge it first thing tomorrow morning (CET :)

**Comment by troglobit** [comment]
Fix(es) merged.

**Comment by Kreijstal** [comment]
Thank you for this work, 6 years later. Simply thank you.
